import { Router } from "express";
const router = Router();
import { authorizeUser } from "../middleware/authorize.mid.js";
import { addVideoToPlaylist, createPlaylist, deletePlaylist, getPlaylistById, getUserPlaylists, removeVideoFromPlaylist } from "../controllers/playlist.controller.js";
router.route("/create-playlist").post(authorizeUser, createPlaylist);
router.route("/delete-playlist").post(authorizeUser, deletePlaylist);
router.route("/add-video-to-playlist").post(authorizeUser, addVideoToPlaylist);
router.route("/remove-video-from-playlist").post(authorizeUser, removeVideoFromPlaylist);
router.route("/get-playlist/:playlistId").get(authorizeUser, getPlaylistById);
router.route("/user-playlists/:playlistId").get(authorizeUser, getUserPlaylists);
export default router;
